# Application Configuration
application.url=https://rahulshettyacademy.com/client/#/auth/login

# User Credentials
user.email=anshika@gmail.com
user.password=Iamking@000

# Product Details
product.name=ADIDAS ORIGINAL
